import { Category } from '../types/category';
import { Token } from '../types/token';
import { generateBackupCodes } from '../utils/totp';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'all',
    name: '全部账号',
    nameKey: 'catAll',
    slug: 'all',
    icon: 'apps',
    color: '#005ac1',
    isDefault: true,
  },
  {
    id: 'work',
    name: '工作办公',
    nameKey: 'catWork',
    slug: 'work',
    icon: 'business_center',
    color: '#535f70',
    isDefault: true,
  },
  {
    id: 'finance',
    name: '金融资产',
    nameKey: 'catFinance',
    slug: 'finance',
    icon: 'account_balance',
    color: '#b45309',
    isDefault: true,
  },
  {
    id: 'social',
    name: '社交媒体',
    nameKey: 'catSocial',
    slug: 'social',
    icon: 'forum',
    color: '#7e22ce',
    isDefault: true,
  },
];

export const DEFAULT_TOKENS: Token[] = [
  {
    id: 'token_fortress_corp',
    userId: 'user_default',
    categoryId: 'work',
    issuer: 'Fortress Corp',
    accountName: 'admin@fortress.co',
    secretKey: 'JBSWY3DPEHPK3PXP',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    iconType: 'shield',
    backupCodes: generateBackupCodes(10),
    notes: 'Primary enterprise security vault root key',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'token_dev_hub',
    userId: 'user_default',
    categoryId: 'work',
    issuer: 'Dev Hub',
    accountName: 'developer@company.net',
    secretKey: 'KZXW65DFOIZXIZLTOBXXE',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    iconType: 'code',
    backupCodes: generateBackupCodes(8),
    notes: 'CI/CD pipeline and cluster deployer',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'token_global_bank',
    userId: 'user_default',
    categoryId: 'finance',
    issuer: 'Global Bank',
    accountName: 'finance@personal.me',
    secretKey: 'MFRGGZDFMY2TOOBWG44A',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    iconType: 'account_balance',
    backupCodes: generateBackupCodes(10),
    notes: 'Treasury & wire authorization account',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'token_google_workspace',
    userId: 'user_default',
    categoryId: 'work',
    issuer: 'Google Workspace',
    accountName: 'alex.mercer@company.com',
    secretKey: 'HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    iconType: 'language',
    backupCodes: generateBackupCodes(10),
    notes: 'Corporate email & drive 2FA',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'token_github_enterprise',
    userId: 'user_default',
    categoryId: 'work',
    issuer: 'GitHub Enterprise',
    accountName: 'alex-engineer',
    secretKey: 'NBSWY3DPEHPK3PXPJBSWY3DP',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    iconType: 'hub',
    backupCodes: generateBackupCodes(12),
    notes: 'Source code & package registry access',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'token_cloudflare_edge',
    userId: 'user_default',
    categoryId: 'work',
    issuer: 'Cloudflare Zero Trust',
    accountName: 'admin@cloudflare.edge',
    secretKey: 'OBXXE5DPOJ2W45DFNZ2XG6A',
    algorithm: 'SHA1',
    digits: 6,
    period: 30,
    iconType: 'cloud',
    backupCodes: generateBackupCodes(10),
    notes: 'Workers & D1 production edge access',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
