import React from 'react';
import { View, Text, TouchableOpacity, Modal, ScrollView, StyleSheet, Platform } from 'react-native';
import { useSettingsStore } from '../../store/useSettingsStore';
import { getColorPalette } from '../../theme/colors';
import { useToast } from '../common/Toast';
import { t } from '../../utils/i18n';
import { Icon } from '../common/Icon';

interface BackupCodesModalProps {
  visible: boolean;
  codes: string[];
  issuer: string;
  onClose: () => void;
}

export const BackupCodesModal: React.FC<BackupCodesModalProps> = ({ visible, codes, issuer, onClose }) => {
  const { showToast } = useToast();
  const themeMode = useSettingsStore((s) => s.themeMode);
  const themeColor = useSettingsStore((s) => s.themeColor);
  const language = useSettingsStore((s) => s.language);

  const isDark = themeMode === 'dark';
  const palette = getColorPalette(themeColor, isDark);

  const fullText = Array.isArray(codes) ? codes.join('\n') : (codes || '');

  const handleCopy = () => {
    if (!fullText) return;
    if (Platform.OS === 'web' && typeof navigator !== 'undefined' && navigator.clipboard) {
      navigator.clipboard.writeText(fullText);
    }
    showToast(t('copiedBackupCodes', language), 'restore_page');
  };

  return (
    <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <View style={styles.overlay}>
        <View
          style={[
            styles.modalContainer,
            {
              backgroundColor: palette.surfaceContainer,
              borderColor: palette.outlineVariant,
            },
          ]}
        >
          {/* Header */}
          <View style={styles.modalHeader}>
            <View style={styles.titleRow}>
              <View style={[styles.iconBox, { backgroundColor: palette.secondaryContainer }]}>
                <Icon name="restore_page" size={20} color={palette.onSecondaryContainer} />
              </View>
              <Text style={[styles.modalTitle, { color: palette.onSurface }]}>
                {issuer} - {t('copyBackupCodes', language)}
              </Text>
            </View>
            <TouchableOpacity onPress={onClose} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
              <Icon name="close" size={22} color={palette.onSurfaceVariant} />
            </TouchableOpacity>
          </View>

          {/* Body */}
          <View style={styles.body}>
            <Text style={[styles.subtitle, { color: palette.onSurfaceVariant }]}>
              {language === 'zh'
                ? '此恢复码由提供商提供，用于在丢失 2FA 设备时恢复访问：'
                : 'Emergency recovery codes generated by the service provider:'}
            </Text>

            <ScrollView style={styles.codeScrollView} showsVerticalScrollIndicator={true}>
              <View
                style={[
                  styles.codeBoxWrapper,
                  {
                    backgroundColor: palette.surfaceContainerLow,
                    borderColor: palette.outlineVariant,
                  },
                ]}
              >
                <Text
                  selectable
                  style={[
                    styles.codeText,
                    {
                      color: palette.onSurface,
                    },
                  ]}
                >
                  {fullText || (language === 'zh' ? '（暂无恢复码）' : 'No recovery codes')}
                </Text>
              </View>
            </ScrollView>
          </View>

          {/* Footer with One-Click Copy */}
          <View style={styles.footer}>
            <TouchableOpacity
              activeOpacity={0.85}
              onPress={handleCopy}
              style={[styles.copyAllBtn, { backgroundColor: palette.primary }]}
            >
              <Icon name="content_copy" size={18} color="#ffffff" />
              <Text style={styles.copyAllText}>
                {language === 'zh' ? '一键复制恢复码' : 'Copy Recovery Codes'}
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 440,
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 16,
    fontWeight: '700',
  },
  body: {
    padding: 18,
  },
  subtitle: {
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  codeScrollView: {
    maxHeight: 220,
  },
  codeBoxWrapper: {
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  codeText: {
    fontFamily: 'JetBrains Mono, monospace',
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 1,
  },
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
  },
  copyAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 9999,
    cursor: 'pointer',
  },
  copyAllText: {
    color: '#ffffff',
    fontFamily: 'Inter, system-ui, sans-serif',
    fontSize: 14,
    fontWeight: '700',
  },
});
